- type: web
  name: unsplash
  env: static
  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: out
  pullRequestPreviewsEnabled: true
  envVars:
    - key: NODE_ENV
      value: production
